<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Vanilla Orange',
                'price' => 22000,
                'description' => 'Minuman rasa vanilla orange',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arengga',
                'price' => 22000,
                'description' => 'Minuman Espresso, Palm Sugar, Fresh Milk',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Berrycano',
                'price' => 25000,
                'description' => 'no',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cookies and Cream',
                'price' => 25000,
                'description' => ' a classic flavor combination typically used in desserts. It features rich vanilla ice cream or milkshake base mixed with crumbled chocolate cookies.',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dancing Caramelo',
                'price' => 25000,
                'description' => 'Original waffle with caramek sauce, vanilla ice cream, sprinkle of almonds',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fresh Mojito',
                'price' => 22000,
                'description' => 'Revitalizing drink crafted from fresh mint leaves, lime wedges, soda water, sugar syrup, and ice cubes.',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vanilla Orange 600ml',
                'price' => 55000,
                'description' => 'Minuman rasa vanilla orange ukuran 600ml',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Sabat',
                'price' => 25000,
                'description' => 'Chocolate waffle with chocholate sauce, Vanilla ice cream and oreo',
                'category' => 'Makanan',
                'image' => 'images/menu/waffle-black-sabat.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waffle Ice Cream',
                'price' => 20000,
                'description' => 'Original waffle with Vanilla ice cream and oreo crumbs',
                'category' => 'Makanan',
                'image' => 'images/menu/waffle-black-sabat.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waffle Nishi Sumatora',
                'price' => 25000,
                'description' => 'Waffle series nishi sumatora',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mentai Beef',
                'price' => 28000,
                'description' => 'Mentai beef dengan kombinasi nasi, shirataki, dan fusilli menghadirkan perpaduan unik rasa Jepang dan tekstur yang menggoda dalam setiap gigitan.',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rice Bowl Nashville Hot Chicken',
                'price' => 28000,
                'description' => 'Rice Bowl Nashville Hot Chicken menyajikan ayam pedas ala Nashville di atas nasi hangat.',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mentai Salmon',
                'price' => 28000,
                'description' => 'Mentai Salmon menawarkan salmon lembut yang dilapisi saus mentai gurih dan dibakar hingga sempurna.',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waffle Green Tea',
                'price' => 18000,
                'description' => 'Waffle Original And Vanilla Ice Cream, Greentea Sauce, And Oreo Crumb On Top',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bella Donna',
                'price' => 20000,
                'description' => 'Mocktail menyegarkan yang memadukan rasa buah segar dengan keharuman bunga',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waffle Whip It',
                'price' => 20000,
                'description' => 'Waffle renyah yang disajikan dengan krim super creamy dan topping seru.',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waffle Peace',
                'price' => 27000,
                'description' => 'Waffle dengan aroma yang menggoda, disajikan dengan stik es krim, saus coklat, potongan stroberi segar, dan remahan almond renyah.',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chip Thrills',
                'price' => 17000,
                'description' => 'Original Waffle With Chocochips In It And Bite Packaging',
                'category' => 'Makanan',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Latte',
                'price' => 25000,
                'description' => 'Minuman kopi yang dicampur dengan susu panas, menciptakan perpaduan yang lembut dan nikmat',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Morning Coffee',
                'price' => 22000,
                'description' => 'Minuman penyemangat pagi yang segar dan menghidupkan, siap menyertai Anda dalam memulai hari dengan semangat.',
                'category' => 'Minuman',
                'image' => 'images/menu/regg-rum.jpg',
                'stock' => rand(10, 100),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // BATASAN MENU
            // BATASAN PRODUK


            // [
            //     'name' => 'Chocup Bliss',
            //     'price' => 25000,
            //     'description' => 'Diced waffle with double ice cream, chocholate Souce, and oreo crumb on top',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Caramel Crunch',
            //     'price' => 25000,
            //     'description' => 'Diced waffle with double ice cream, Homemade Caramel Sauce and pop corn on top',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Regg-Rum',
            //     'price' => 25000,
            //     'description' => 'Espresso, Dark Chocolate With Jamaican Rum Sensation',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Peace Waffle',
            //     'price' => 25000,
            //     'description' => 'Original Waffle With Feast Walls Vanilla Ice Cream, Chocolate Sauce, Strawberry And Almond Slice On Top',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Cinaton',
            //     'price' => 22000,
            //     'description' => 'Espresso, Cinnamon, Fresh Milk',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Gypsy Sweet',
            //     'price' => 25000,
            //     'description' => 'Espresso, Irish Cream, Fresh Milk',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Lychee Tea',
            //     'price' => 22000,
            //     'description' => 'Tea with sweet sugar, fresh lychee, and ice cubes.',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Iced Chocolate',
            //     'price' => 25000,
            //     'description' => 'Refreshing beverage made from a blend of cold chocolate milk and ice cubes.',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Iced Matcha',
            //     'price' => 25000,
            //     'description' => 'Refreshing drink consisting of chilled matcha powder, milk or milk alternative, sweetener, and ice cubes',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // [
            //     'name' => 'Regal and Cream',
            //     'price' => 25000,
            //     'description' => 'Freshmilk, Regal Biscuit Blended With Ice Cream',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Vanilla Rainbow',
            //     'price' => 25000,
            //     'description' => 'Freshmilk Blended With Walls Rainbow Ice Cream',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Virgin Mojito',
            //     'price' => 22000,
            //     'description' => 'no deskription',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Rooftop Sunset',
            //     'price' => 22000,
            //     'description' => 'Soda, Orange And Strawberry Flavor, Lemon Slice And Soda Water',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Americano',
            //     'price' => 22000,
            //     'description' => 'no',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

            // [
            //     'name' => 'Cappucino',
            //     'price' => 25000,
            //     'description' => 'no',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Vanilla',
            //     'price' => 25000,
            //     'description' => 'no',
            //     'category' => 'Minuman',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Waffle Nuttela',
            //     'price' => 20000,
            //     'description' => 'Waffle Original With Nutella Spread And Vanilla Ice Cream, Chocolate Sauce, And Oreo Crumb On Top',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Waffle Dark Choco',
            //     'price' => 15000,
            //     'description' => 'Waffle Original And Vanilla Ice Cream, Chocolate Sauce, And Oreo Crumb On Top',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'name' => 'Bitella',
            //     'price' => 25000,
            //     'description' => 'Original Waffle Inject Nutella Topping And Bite Packaging',
            //     'category' => 'Makanan',
            //     'image' => 'images/menu/regg-rum.jpg',
            //     'stock' => rand(10, 100),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],

        ];
        DB::table('products')->insert($data);
    }
}
